//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of ActionItem data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class ActionItem
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the class_name column.
        /// </summary>
        [DataMember]
        public string class_name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the method_name column.
        /// </summary>
        [DataMember]
        public string method_name { get; set; }
    }
}
