//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of AdvancedField data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class AdvancedField
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the entity_id column.
        /// </summary>
        [DataMember]
        public int entity_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the type_id column.
        /// </summary>
        [DataMember]
        public int type_id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the name column.
        /// </summary>
        [DataMember]
        public string name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the desc column.
        /// </summary>
        [DataMember]
        public string desc { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the is_mandatory column.
        /// </summary>
        [DataMember]
        public bool is_mandatory { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the is_unique column.
        /// </summary>
        [DataMember]
        public bool is_unique { get; set; }
    }
}
