//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of AmountCycle data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class AmountCycle
    {
        /// <summary>
        /// Gets or sets a int value for the cycle_id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int cycle_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the number column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int number { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount_min column.
        /// </summary>
        [DataMember]
        public decimal amount_min { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount_max column.
        /// </summary>
        [DataMember]
        public decimal amount_max { get; set; }
    }
}
