//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of ChartOfAccount data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class ChartOfAccount
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the account_number column.
        /// </summary>
        [DataMember]
        public string account_number { get; set; }

        /// <summary>
        /// Gets or sets a string value for the label column.
        /// </summary>
        [DataMember]
        public string label { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the debit_plus column.
        /// </summary>
        [DataMember]
        public bool debit_plus { get; set; }

        /// <summary>
        /// Gets or sets a string value for the type_code column.
        /// </summary>
        [DataMember]
        public string type_code { get; set; }

        /// <summary>
        /// Gets or sets a short value for the account_category_id column.
        /// </summary>
        [DataMember]
        public short account_category_id { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the type column.
        /// </summary>
        [DataMember]
        public bool type { get; set; }

        /// <summary>
        /// Gets or sets a int value for the parent_account_id column.
        /// </summary>
        [DataMember]
        public int parent_account_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the lft column.
        /// </summary>
        [DataMember]
        public int lft { get; set; }

        /// <summary>
        /// Gets or sets a int value for the rgt column.
        /// </summary>
        [DataMember]
        public int rgt { get; set; }
    }
}
