//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of ConsolidatedData data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class ConsolidatedData
    {
        /// <summary>
        /// Gets or sets a string value for the branch column.
        /// </summary>
        [DataMember]
        public string branch { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the date column.
        /// </summary>
        [DataMember]
        public DateTime date { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the olb column.
        /// </summary>
        [DataMember]
        public decimal olb { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par column.
        /// </summary>
        [DataMember]
        public decimal par { get; set; }

        /// <summary>
        /// Gets or sets a int value for the number_of_clients column.
        /// </summary>
        [DataMember]
        public int number_of_clients { get; set; }

        /// <summary>
        /// Gets or sets a int value for the number_of_contracts column.
        /// </summary>
        [DataMember]
        public int number_of_contracts { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the disbursements_amount column.
        /// </summary>
        [DataMember]
        public decimal disbursements_amount { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the disbursements_fees column.
        /// </summary>
        [DataMember]
        public decimal disbursements_fees { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the repayments_principal column.
        /// </summary>
        [DataMember]
        public decimal repayments_principal { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the repayments_interest column.
        /// </summary>
        [DataMember]
        public decimal repayments_interest { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the repayments_commissions column.
        /// </summary>
        [DataMember]
        public decimal repayments_commissions { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the repayments_penalties column.
        /// </summary>
        [DataMember]
        public decimal repayments_penalties { get; set; }
    }
}
