//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of Credit data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Credit
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the package_id column.
        /// </summary>
        [DataMember]
        public int package_id { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount column.
        /// </summary>
        [DataMember]
        public decimal amount { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the interest_rate column.
        /// </summary>
        [DataMember]
        public decimal interest_rate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the installment_type column.
        /// </summary>
        [DataMember]
        public int installment_type { get; set; }

        /// <summary>
        /// Gets or sets a int value for the nb_of_installment column.
        /// </summary>
        [DataMember]
        public int nb_of_installment { get; set; }

        /// <summary>
        /// Gets or sets a double value for the anticipated_total_repayment_penalties column.
        /// </summary>
        [DataMember]
        public double anticipated_total_repayment_penalties { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the disbursed column.
        /// </summary>
        [DataMember]
        public bool disbursed { get; set; }

        /// <summary>
        /// Gets or sets a int value for the loanofficer_id column.
        /// </summary>
        [DataMember]
        public int loanofficer_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the grace_period column.
        /// </summary>
        [DataMember]
        public int grace_period { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the written_off column.
        /// </summary>
        [DataMember]
        public bool written_off { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the rescheduled column.
        /// </summary>
        [DataMember]
        public bool rescheduled { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the bad_loan column.
        /// </summary>
        [DataMember]
        public bool bad_loan { get; set; }

        /// <summary>
        /// Gets or sets a double value for the non_repayment_penalties_based_on_overdue_principal column.
        /// </summary>
        [DataMember]
        public double non_repayment_penalties_based_on_overdue_principal { get; set; }

        /// <summary>
        /// Gets or sets a double value for the non_repayment_penalties_based_on_initial_amount column.
        /// </summary>
        [DataMember]
        public double non_repayment_penalties_based_on_initial_amount { get; set; }

        /// <summary>
        /// Gets or sets a double value for the non_repayment_penalties_based_on_olb column.
        /// </summary>
        [DataMember]
        public double non_repayment_penalties_based_on_olb { get; set; }

        /// <summary>
        /// Gets or sets a double value for the non_repayment_penalties_based_on_overdue_interest column.
        /// </summary>
        [DataMember]
        public double non_repayment_penalties_based_on_overdue_interest { get; set; }

        /// <summary>
        /// Gets or sets a int value for the fundingLine_id column.
        /// </summary>
        [DataMember]
        public int fundingLine_id { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the synchronize column.
        /// </summary>
        [DataMember]
        public bool synchronize { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the interest column.
        /// </summary>
        [DataMember]
        public decimal interest { get; set; }

        /// <summary>
        /// Gets or sets a int value for the grace_period_of_latefees column.
        /// </summary>
        [DataMember]
        public int grace_period_of_latefees { get; set; }

        /// <summary>
        /// Gets or sets a double value for the anticipated_partial_repayment_penalties column.
        /// </summary>
        [DataMember]
        public double anticipated_partial_repayment_penalties { get; set; }

        /// <summary>
        /// Gets or sets a int value for the number_of_drawings_loc column.
        /// </summary>
        [DataMember]
        public int number_of_drawings_loc { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount_under_loc column.
        /// </summary>
        [DataMember]
        public decimal amount_under_loc { get; set; }

        /// <summary>
        /// Gets or sets a int value for the maturity_loc column.
        /// </summary>
        [DataMember]
        public int maturity_loc { get; set; }

        /// <summary>
        /// Gets or sets a short value for the anticipated_partial_repayment_base column.
        /// </summary>
        [DataMember]
        public short anticipated_partial_repayment_base { get; set; }

        /// <summary>
        /// Gets or sets a short value for the anticipated_total_repayment_base column.
        /// </summary>
        [DataMember]
        public short anticipated_total_repayment_base { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the schedule_changed column.
        /// </summary>
        [DataMember]
        public bool schedule_changed { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount_min column.
        /// </summary>
        [DataMember]
        public decimal amount_min { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount_max column.
        /// </summary>
        [DataMember]
        public decimal amount_max { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the ir_min column.
        /// </summary>
        [DataMember]
        public decimal ir_min { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the ir_max column.
        /// </summary>
        [DataMember]
        public decimal ir_max { get; set; }

        /// <summary>
        /// Gets or sets a int value for the nmb_of_inst_min column.
        /// </summary>
        [DataMember]
        public int nmb_of_inst_min { get; set; }

        /// <summary>
        /// Gets or sets a int value for the nmb_of_inst_max column.
        /// </summary>
        [DataMember]
        public int nmb_of_inst_max { get; set; }

        /// <summary>
        /// Gets or sets a int value for the loan_cycle column.
        /// </summary>
        [DataMember]
        public int loan_cycle { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the insurance column.
        /// </summary>
        [DataMember]
        public decimal insurance { get; set; }

        /// <summary>
        /// Gets or sets a int value for the exotic_id column.
        /// </summary>
        [DataMember]
        public int exotic_id { get; set; }
    }
}
