//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of CycleParameter data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class CycleParameter
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the loan_cycle column.
        /// </summary>
        [DataMember]
        public int loan_cycle { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the min column.
        /// </summary>
        [DataMember]
        public decimal min { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the max column.
        /// </summary>
        [DataMember]
        public decimal max { get; set; }

        /// <summary>
        /// Gets or sets a int value for the cycle_object_id column.
        /// </summary>
        [DataMember]
        public int cycle_object_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the cycle_id column.
        /// </summary>
        [DataMember]
        public int cycle_id { get; set; }
    }
}
