//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of FundingLineEvent data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class FundingLineEvent
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the code column.
        /// </summary>
        [DataMember]
        public string code { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount column.
        /// </summary>
        [DataMember]
        public decimal amount { get; set; }

        /// <summary>
        /// Gets or sets a short value for the direction column.
        /// </summary>
        [DataMember]
        public short direction { get; set; }

        /// <summary>
        /// Gets or sets a int value for the fundingline_id column.
        /// </summary>
        [DataMember]
        public int fundingline_id { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the deleted column.
        /// </summary>
        [DataMember]
        public bool deleted { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the creation_date column.
        /// </summary>
        [DataMember]
        public DateTime creation_date { get; set; }

        /// <summary>
        /// Gets or sets a short value for the type column.
        /// </summary>
        [DataMember]
        public short type { get; set; }

        /// <summary>
        /// Gets or sets a int value for the user_id column.
        /// </summary>
        [DataMember]
        public int user_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contract_event_id column.
        /// </summary>
        [DataMember]
        public int contract_event_id { get; set; }
    }
}
