//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of LoanShareAmount data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class LoanShareAmount
    {
        /// <summary>
        /// Gets or sets a int value for the person_id column.
        /// </summary>
        [DataMember]
        public int person_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the group_id column.
        /// </summary>
        [DataMember]
        public int group_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contract_id column.
        /// </summary>
        [DataMember]
        public int contract_id { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount column.
        /// </summary>
        [DataMember]
        public decimal amount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the event_id column.
        /// </summary>
        [DataMember]
        public int event_id { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the payment_date column.
        /// </summary>
        [DataMember]
        public DateTime payment_date { get; set; }
    }
}
