//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of Questionnaire data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Questionnaire
    {
        /// <summary>
        /// Gets or sets a string value for the Name column.
        /// </summary>
        [DataMember]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Country column.
        /// </summary>
        [DataMember]
        public string Country { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a string value for the PositionInCompony column.
        /// </summary>
        [DataMember]
        public string PositionInCompony { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OtherMessages column.
        /// </summary>
        [DataMember]
        public string OtherMessages { get; set; }

        /// <summary>
        /// Gets or sets a string value for the GrossPortfolio column.
        /// </summary>
        [DataMember]
        public string GrossPortfolio { get; set; }

        /// <summary>
        /// Gets or sets a string value for the NumberOfClients column.
        /// </summary>
        [DataMember]
        public string NumberOfClients { get; set; }

        /// <summary>
        /// Gets or sets a string value for the PersonName column.
        /// </summary>
        [DataMember]
        public string PersonName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Phone column.
        /// </summary>
        [DataMember]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Skype column.
        /// </summary>
        [DataMember]
        public string Skype { get; set; }

        /// <summary>
        /// Gets or sets a string value for the PurposeOfUsage column.
        /// </summary>
        [DataMember]
        public string PurposeOfUsage { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the is_sent column.
        /// </summary>
        [DataMember]
        public bool is_sent { get; set; }
    }
}
