//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of Rep_Par_Analysis_Data data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Rep_Par_Analysis_Data
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the branch_name column.
        /// </summary>
        [DataMember]
        public string branch_name { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the load_date column.
        /// </summary>
        [DataMember]
        public DateTime load_date { get; set; }

        /// <summary>
        /// Gets or sets a string value for the break_down column.
        /// </summary>
        [DataMember]
        public string break_down { get; set; }

        /// <summary>
        /// Gets or sets a string value for the break_down_type column.
        /// </summary>
        [DataMember]
        public string break_down_type { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the olb column.
        /// </summary>
        [DataMember]
        public decimal olb { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par column.
        /// </summary>
        [DataMember]
        public decimal par { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contracts column.
        /// </summary>
        [DataMember]
        public int contracts { get; set; }

        /// <summary>
        /// Gets or sets a int value for the clients column.
        /// </summary>
        [DataMember]
        public int clients { get; set; }

        /// <summary>
        /// Gets or sets a int value for the all_contracts column.
        /// </summary>
        [DataMember]
        public int all_contracts { get; set; }

        /// <summary>
        /// Gets or sets a int value for the all_clients column.
        /// </summary>
        [DataMember]
        public int all_clients { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par_30 column.
        /// </summary>
        [DataMember]
        public decimal par_30 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contracts_30 column.
        /// </summary>
        [DataMember]
        public int contracts_30 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the clients_30 column.
        /// </summary>
        [DataMember]
        public int clients_30 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par_1_30 column.
        /// </summary>
        [DataMember]
        public decimal par_1_30 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contracts_1_30 column.
        /// </summary>
        [DataMember]
        public int contracts_1_30 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the clients_1_30 column.
        /// </summary>
        [DataMember]
        public int clients_1_30 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par_31_60 column.
        /// </summary>
        [DataMember]
        public decimal par_31_60 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contracts_31_60 column.
        /// </summary>
        [DataMember]
        public int contracts_31_60 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the clients_31_60 column.
        /// </summary>
        [DataMember]
        public int clients_31_60 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par_61_90 column.
        /// </summary>
        [DataMember]
        public decimal par_61_90 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contracts_61_90 column.
        /// </summary>
        [DataMember]
        public int contracts_61_90 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the clients_61_90 column.
        /// </summary>
        [DataMember]
        public int clients_61_90 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par_91_180 column.
        /// </summary>
        [DataMember]
        public decimal par_91_180 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contracts_91_180 column.
        /// </summary>
        [DataMember]
        public int contracts_91_180 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the clients_91_180 column.
        /// </summary>
        [DataMember]
        public int clients_91_180 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par_181_365 column.
        /// </summary>
        [DataMember]
        public decimal par_181_365 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contracts_181_365 column.
        /// </summary>
        [DataMember]
        public int contracts_181_365 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the clients_181_365 column.
        /// </summary>
        [DataMember]
        public int clients_181_365 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the par_365 column.
        /// </summary>
        [DataMember]
        public decimal par_365 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contracts_365 column.
        /// </summary>
        [DataMember]
        public int contracts_365 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the clients_365 column.
        /// </summary>
        [DataMember]
        public int clients_365 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the break_down_id column.
        /// </summary>
        [DataMember]
        public int break_down_id { get; set; }
    }
}
