//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of Rep_OLB_and_LLP_Data data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Rep_OLB_and_LLP_Data
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the branch_name column.
        /// </summary>
        [DataMember]
        public string branch_name { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the load_date column.
        /// </summary>
        [DataMember]
        public DateTime load_date { get; set; }

        /// <summary>
        /// Gets or sets a string value for the contract_code column.
        /// </summary>
        [DataMember]
        public string contract_code { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the olb column.
        /// </summary>
        [DataMember]
        public decimal olb { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the interest column.
        /// </summary>
        [DataMember]
        public decimal interest { get; set; }

        /// <summary>
        /// Gets or sets a int value for the late_days column.
        /// </summary>
        [DataMember]
        public int late_days { get; set; }

        /// <summary>
        /// Gets or sets a string value for the client_name column.
        /// </summary>
        [DataMember]
        public string client_name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the loan_officer_name column.
        /// </summary>
        [DataMember]
        public string loan_officer_name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the product_name column.
        /// </summary>
        [DataMember]
        public string product_name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the district_name column.
        /// </summary>
        [DataMember]
        public string district_name { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the start_date column.
        /// </summary>
        [DataMember]
        public DateTime start_date { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the close_date column.
        /// </summary>
        [DataMember]
        public DateTime close_date { get; set; }

        /// <summary>
        /// Gets or sets a int value for the range_from column.
        /// </summary>
        [DataMember]
        public int range_from { get; set; }

        /// <summary>
        /// Gets or sets a int value for the range_to column.
        /// </summary>
        [DataMember]
        public int range_to { get; set; }

        /// <summary>
        /// Gets or sets a int value for the llp_rate column.
        /// </summary>
        [DataMember]
        public int llp_rate { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the llp column.
        /// </summary>
        [DataMember]
        public decimal llp { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the rescheduled column.
        /// </summary>
        [DataMember]
        public bool rescheduled { get; set; }
    }
}
