//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of RepaymentEvent data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class RepaymentEvent
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the past_due_days column.
        /// </summary>
        [DataMember]
        public int past_due_days { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the principal column.
        /// </summary>
        [DataMember]
        public decimal principal { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the interests column.
        /// </summary>
        [DataMember]
        public decimal interests { get; set; }

        /// <summary>
        /// Gets or sets a int value for the installment_number column.
        /// </summary>
        [DataMember]
        public int installment_number { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the commissions column.
        /// </summary>
        [DataMember]
        public decimal commissions { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the penalties column.
        /// </summary>
        [DataMember]
        public decimal penalties { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the calculated_penalties column.
        /// </summary>
        [DataMember]
        public decimal calculated_penalties { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the written_off_penalties column.
        /// </summary>
        [DataMember]
        public decimal written_off_penalties { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the unpaid_penalties column.
        /// </summary>
        [DataMember]
        public decimal unpaid_penalties { get; set; }
    }
}
