//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of ReschedulingOfALoanEvent data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class ReschedulingOfALoanEvent
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount column.
        /// </summary>
        [DataMember]
        public decimal amount { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the interest column.
        /// </summary>
        [DataMember]
        public decimal interest { get; set; }

        /// <summary>
        /// Gets or sets a int value for the nb_of_maturity column.
        /// </summary>
        [DataMember]
        public int nb_of_maturity { get; set; }

        /// <summary>
        /// Gets or sets a int value for the date_offset column.
        /// </summary>
        [DataMember]
        public int date_offset { get; set; }

        /// <summary>
        /// Gets or sets a int value for the grace_period column.
        /// </summary>
        [DataMember]
        public int grace_period { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the charge_interest_during_shift column.
        /// </summary>
        [DataMember]
        public bool charge_interest_during_shift { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the charge_interest_during_grace_period column.
        /// </summary>
        [DataMember]
        public bool charge_interest_during_grace_period { get; set; }
    }
}
