//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of SavingEvent data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class SavingEvent
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the user_id column.
        /// </summary>
        [DataMember]
        public int user_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the contract_id column.
        /// </summary>
        [DataMember]
        public int contract_id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the code column.
        /// </summary>
        [DataMember]
        public string code { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the amount column.
        /// </summary>
        [DataMember]
        public decimal amount { get; set; }

        /// <summary>
        /// Gets or sets a string value for the description column.
        /// </summary>
        [DataMember]
        public string description { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the deleted column.
        /// </summary>
        [DataMember]
        public bool deleted { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the creation_date column.
        /// </summary>
        [DataMember]
        public DateTime creation_date { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the cancelable column.
        /// </summary>
        [DataMember]
        public bool cancelable { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the is_fired column.
        /// </summary>
        [DataMember]
        public bool is_fired { get; set; }

        /// <summary>
        /// Gets or sets a string value for the related_contract_code column.
        /// </summary>
        [DataMember]
        public string related_contract_code { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the fees column.
        /// </summary>
        [DataMember]
        public decimal fees { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the is_exported column.
        /// </summary>
        [DataMember]
        public bool is_exported { get; set; }

        /// <summary>
        /// Gets or sets a short value for the savings_method column.
        /// </summary>
        [DataMember]
        public short savings_method { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the pending column.
        /// </summary>
        [DataMember]
        public bool pending { get; set; }

        /// <summary>
        /// Gets or sets a int value for the pending_event_id column.
        /// </summary>
        [DataMember]
        public int pending_event_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the teller_id column.
        /// </summary>
        [DataMember]
        public int teller_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the loan_event_id column.
        /// </summary>
        [DataMember]
        public int loan_event_id { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the cancel_date column.
        /// </summary>
        [DataMember]
        public DateTime cancel_date { get; set; }
    }
}
