//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:26:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSaccoWeb.Entities
{
    /// <summary>
    /// Represents a row of VillagesAttendance data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class VillagesAttendance
    {
        /// <summary>
        /// Gets or sets a int value for the id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the village_id column.
        /// </summary>
        [DataMember]
        public int village_id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the person_id column.
        /// </summary>
        [DataMember]
        public int person_id { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the date column.
        /// </summary>
        [DataMember]
        public DateTime date { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the attended column.
        /// </summary>
        [DataMember]
        public bool attended { get; set; }

        /// <summary>
        /// Gets or sets a string value for the comment column.
        /// </summary>
        [DataMember]
        public string comment { get; set; }

        /// <summary>
        /// Gets or sets a int value for the loan_id column.
        /// </summary>
        [DataMember]
        public int loan_id { get; set; }
    }
}
