//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 07:43:03 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiSaccoWeb.Entities;
using SBiSaccoWeb.Data;


namespace SBiSaccoWeb.Business
{
    /// <summary>
    /// Currencies business component.
    /// </summary>
    public partial class CurrenciesComponent
    {
        /// <summary>
        /// GetCurrencies business method. 
        /// </summary>
        /// <returns>Returns a List<Currency> object.</returns>
        public List<Currency> GetCurrencies()
        {
            List<Currency> result = default(List<Currency>);

            // Data access component declarations.
            CurrencyDAC currencyDAC = new CurrencyDAC();

            // Step 1 - Calling Select on CurrencyDAC.
            result = currencyDAC.Select();
            return result;

        }

        /// <summary>
        /// CreateCurrency business method. 
        /// </summary>
        /// <param name="currency">A currency value.</param>
        /// <returns>Returns a Currency object.</returns>
        public Currency CreateCurrency(Currency currency)
        {
            Currency result = default(Currency);

            // Data access component declarations.
            CurrencyDAC currencyDAC = new CurrencyDAC();

            // Step 1 - Calling Create on CurrencyDAC.
            result = currencyDAC.Create(currency);
            return result;

        }

        /// <summary>
        /// DeleteCurrency business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteCurrency(int id)
        {
            // Data access component declarations.
            CurrencyDAC currencyDAC = new CurrencyDAC();

            // Step 1 - Calling DeleteById on CurrencyDAC.
            currencyDAC.DeleteById(id);

        }

        /// <summary>
        /// SelectCurrency business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>Returns a Currency object.</returns>
        public Currency SelectCurrency(int id)
        {
            Currency result = default(Currency);

            // Data access component declarations.
            CurrencyDAC currencyDAC = new CurrencyDAC();

            // Step 1 - Calling SelectById on CurrencyDAC.
            result = currencyDAC.SelectById(id);
            return result;

        }

        /// <summary>
        /// UpdateCurrency business method. 
        /// </summary>
        /// <param name="currency">A currency value.</param>
        public void UpdateCurrency(Currency currency)
        {
            // Data access component declarations.
            CurrencyDAC currencyDAC = new CurrencyDAC();

            // Step 1 - Calling UpdateById on CurrencyDAC.
            currencyDAC.UpdateById(currency);

        }
    }
}
