//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 11:47:58 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiSaccoWeb.Entities;
using SBiSaccoWeb.Data;


namespace SBiSaccoWeb.Business
{
    /// <summary>
    /// SavingsProducts business component.
    /// </summary>
    public partial class SavingsProductsComponent
    {
        /// <summary>
        /// GetAllSavingsProducts business method. 
        /// </summary>
        /// <returns>Returns a List<SavingProduct> object.</returns>
        public List<SavingProduct> GetAllSavingsProducts()
        {
            List<SavingProduct> result = default(List<SavingProduct>);

            // Data access component declarations.
            SavingProductDAC savingProductDAC = new SavingProductDAC();

            // Step 1 - Calling Select on SavingProductDAC.
            result = savingProductDAC.Select();
            return result;

        }

        /// <summary>
        /// GetSavingsProduct business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>Returns a SavingProduct object.</returns>
        public SavingProduct GetSavingsProduct(int id)
        {
            SavingProduct result = default(SavingProduct);

            // Data access component declarations.
            SavingProductDAC savingProductDAC = new SavingProductDAC();

            // Step 1 - Calling SelectById on SavingProductDAC.
            result = savingProductDAC.SelectById(id);
            return result;

        }

        /// <summary>
        /// CreateSavingsProduct business method. 
        /// </summary>
        /// <param name="savingProduct">A savingProduct value.</param>
        /// <returns>Returns a SavingProduct object.</returns>
        public SavingProduct CreateSavingsProduct(SavingProduct savingProduct)
        {
            SavingProduct result = default(SavingProduct);

            // Data access component declarations.
            SavingProductDAC savingProductDAC = new SavingProductDAC();

            // Step 1 - Calling Create on SavingProductDAC.
            result = savingProductDAC.Create(savingProduct);
            return result;

        }

        /// <summary>
        /// UpdateSavingsProduct business method. 
        /// </summary>
        /// <param name="savingProduct">A savingProduct value.</param>
        public void UpdateSavingsProduct(SavingProduct savingProduct)
        {
            // Data access component declarations.
            SavingProductDAC savingProductDAC = new SavingProductDAC();

            // Step 1 - Calling UpdateById on SavingProductDAC.
            savingProductDAC.UpdateById(savingProduct);

        }

        /// <summary>
        /// DeleteSavingsProduct business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteSavingsProduct(int id)
        {
            // Data access component declarations.
            SavingProductDAC savingProductDAC = new SavingProductDAC();

            // Step 1 - Calling DeleteById on SavingProductDAC.
            savingProductDAC.DeleteById(id);

        }
    }
}
