//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:44 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// ActionItems data access component. Manages CRUD operations for the ActionItems table.
    /// </summary>
    public partial class ActionItemDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the ActionItems table.
        /// </summary>
        /// <param name="actionItem">A ActionItem object.</param>
        /// <returns>An updated ActionItem object.</returns>
        public ActionItem Create(ActionItem actionItem)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.ActionItems ([class_name], [method_name]) " +
                "VALUES(@class_name, @method_name); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@class_name", DbType.String, actionItem.class_name);
                db.AddInParameter(cmd, "@method_name", DbType.String, actionItem.method_name);

                // Get the primary key value.
                actionItem.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return actionItem;
        }

        /// <summary>
        /// Updates an existing row in the ActionItems table.
        /// </summary>
        /// <param name="actionItem">A ActionItem entity object.</param>
        public void UpdateById(ActionItem actionItem)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.ActionItems " +
                "SET " +
                    "[class_name]=@class_name, " +
                    "[method_name]=@method_name " +
                "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@class_name", DbType.String, actionItem.class_name);
                db.AddInParameter(cmd, "@method_name", DbType.String, actionItem.method_name);
                db.AddInParameter(cmd, "@id", DbType.Int32, actionItem.id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the ActionItems table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.ActionItems " +
                                         "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the ActionItems table.
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>A ActionItem object with data populated from the database.</returns>
        public ActionItem SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [id], [class_name], [method_name] " +
                "FROM dbo.ActionItems  " +
                "WHERE [id]=@id ";

            ActionItem actionItem = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new ActionItem
                        actionItem = new ActionItem();

                        // Read values.
                        actionItem.id = base.GetDataValue<int>(dr, "id");
                        actionItem.class_name = base.GetDataValue<string>(dr, "class_name");
                        actionItem.method_name = base.GetDataValue<string>(dr, "method_name");
                    }
                }
            }

            return actionItem;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the ActionItems table.
        /// </summary>
        /// <returns>A collection of ActionItem objects.</returns>		
        public List<ActionItem> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [class_name], [method_name] " +
                "FROM dbo.ActionItems ";

            List<ActionItem> result = new List<ActionItem>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new ActionItem
                        ActionItem actionItem = new ActionItem();

                        // Read values.
                        actionItem.id = base.GetDataValue<int>(dr, "id");
                        actionItem.class_name = base.GetDataValue<string>(dr, "class_name");
                        actionItem.method_name = base.GetDataValue<string>(dr, "method_name");

                        // Add to List.
                        result.Add(actionItem);
                    }
                }
            }

            return result;
        }
    }
}

