//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:44 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// Branches data access component. Manages CRUD operations for the Branches table.
    /// </summary>
    public partial class BranchDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the Branches table.
        /// </summary>
        /// <param name="branch">A Branch object.</param>
        /// <returns>An updated Branch object.</returns>
        public Branch Create(Branch branch)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.Branches ([name], [deleted], [code], [address], [description]) " +
                "VALUES(@name, @deleted, @code, @address, @description); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@name", DbType.String, branch.name);
                db.AddInParameter(cmd, "@deleted", DbType.Boolean, branch.deleted);
                db.AddInParameter(cmd, "@code", DbType.String, branch.code);
                db.AddInParameter(cmd, "@address", DbType.String, branch.address);
                db.AddInParameter(cmd, "@description", DbType.String, branch.description);

                // Get the primary key value.
                branch.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return branch;
        }

        /// <summary>
        /// Updates an existing row in the Branches table.
        /// </summary>
        /// <param name="branch">A Branch entity object.</param>
        public void UpdateById(Branch branch)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.Branches " +
                "SET " +
                    "[name]=@name, " +
                    "[deleted]=@deleted, " +
                    "[code]=@code, " +
                    "[address]=@address, " +
                    "[description]=@description " +
                "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@name", DbType.String, branch.name);
                db.AddInParameter(cmd, "@deleted", DbType.Boolean, branch.deleted);
                db.AddInParameter(cmd, "@code", DbType.String, branch.code);
                db.AddInParameter(cmd, "@address", DbType.String, branch.address);
                db.AddInParameter(cmd, "@description", DbType.String, branch.description);
                db.AddInParameter(cmd, "@id", DbType.Int32, branch.id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the Branches table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.Branches " +
                                         "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the Branches table.
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>A Branch object with data populated from the database.</returns>
        public Branch SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [id], [name], [deleted], [code], [address], [description] " +
                "FROM dbo.Branches  " +
                "WHERE [id]=@id ";

            Branch branch = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new Branch
                        branch = new Branch();

                        // Read values.
                        branch.id = base.GetDataValue<int>(dr, "id");
                        branch.name = base.GetDataValue<string>(dr, "name");
                        branch.deleted = base.GetDataValue<bool>(dr, "deleted");
                        branch.code = base.GetDataValue<string>(dr, "code");
                        branch.address = base.GetDataValue<string>(dr, "address");
                        branch.description = base.GetDataValue<string>(dr, "description");
                    }
                }
            }

            return branch;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the Branches table.
        /// </summary>
        /// <returns>A collection of Branch objects.</returns>		
        public List<Branch> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [name], [deleted], [code], [address], [description] " +
                "FROM dbo.Branches ";

            List<Branch> result = new List<Branch>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new Branch
                        Branch branch = new Branch();

                        // Read values.
                        branch.id = base.GetDataValue<int>(dr, "id");
                        branch.name = base.GetDataValue<string>(dr, "name");
                        branch.deleted = base.GetDataValue<bool>(dr, "deleted");
                        branch.code = base.GetDataValue<string>(dr, "code");
                        branch.address = base.GetDataValue<string>(dr, "address");
                        branch.description = base.GetDataValue<string>(dr, "description");

                        // Add to List.
                        result.Add(branch);
                    }
                }
            }

            return result;
        }
    }
}

