//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// CollateralPropertyTypes data access component. Manages CRUD operations for the CollateralPropertyTypes table.
    /// </summary>
    public partial class CollateralPropertyTypeDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the CollateralPropertyTypes table.
        /// </summary>
        /// <param name="collateralPropertyType">A CollateralPropertyType object.</param>
        /// <returns>An updated CollateralPropertyType object.</returns>
        public CollateralPropertyType Create(CollateralPropertyType collateralPropertyType)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.CollateralPropertyTypes ([name]) " +
                "VALUES(@name); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@name", DbType.String, collateralPropertyType.name);

                // Get the primary key value.
                collateralPropertyType.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return collateralPropertyType;
        }

        /// <summary>
        /// Updates an existing row in the CollateralPropertyTypes table.
        /// </summary>
        /// <param name="collateralPropertyType">A CollateralPropertyType entity object.</param>
        public void UpdateById(CollateralPropertyType collateralPropertyType)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.CollateralPropertyTypes " +
                "SET " +
                    "[name]=@name " +
                "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@name", DbType.String, collateralPropertyType.name);
                db.AddInParameter(cmd, "@id", DbType.Int32, collateralPropertyType.id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the CollateralPropertyTypes table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.CollateralPropertyTypes " +
                                         "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the CollateralPropertyTypes table.
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>A CollateralPropertyType object with data populated from the database.</returns>
        public CollateralPropertyType SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [id], [name] " +
                "FROM dbo.CollateralPropertyTypes  " +
                "WHERE [id]=@id ";

            CollateralPropertyType collateralPropertyType = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new CollateralPropertyType
                        collateralPropertyType = new CollateralPropertyType();

                        // Read values.
                        collateralPropertyType.id = base.GetDataValue<int>(dr, "id");
                        collateralPropertyType.name = base.GetDataValue<string>(dr, "name");
                    }
                }
            }

            return collateralPropertyType;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the CollateralPropertyTypes table.
        /// </summary>
        /// <returns>A collection of CollateralPropertyType objects.</returns>		
        public List<CollateralPropertyType> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [name] " +
                "FROM dbo.CollateralPropertyTypes ";

            List<CollateralPropertyType> result = new List<CollateralPropertyType>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new CollateralPropertyType
                        CollateralPropertyType collateralPropertyType = new CollateralPropertyType();

                        // Read values.
                        collateralPropertyType.id = base.GetDataValue<int>(dr, "id");
                        collateralPropertyType.name = base.GetDataValue<string>(dr, "name");

                        // Add to List.
                        result.Add(collateralPropertyType);
                    }
                }
            }

            return result;
        }
    }
}

