//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:44 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// CollateralProperties data access component. Manages CRUD operations for the CollateralProperties table.
    /// </summary>
    public partial class CollateralPropertyDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the CollateralProperties table.
        /// </summary>
        /// <param name="collateralProperty">A CollateralProperty object.</param>
        /// <returns>An updated CollateralProperty object.</returns>
        public CollateralProperty Create(CollateralProperty collateralProperty)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.CollateralProperties ([product_id], [type_id], [name], [desc]) " +
                "VALUES(@product_id, @type_id, @name, @desc); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@product_id", DbType.Int32, collateralProperty.product_id);
                db.AddInParameter(cmd, "@type_id", DbType.Int32, collateralProperty.type_id);
                db.AddInParameter(cmd, "@name", DbType.String, collateralProperty.name);
                db.AddInParameter(cmd, "@desc", DbType.String, collateralProperty.desc);

                // Get the primary key value.
                collateralProperty.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return collateralProperty;
        }

        /// <summary>
        /// Updates an existing row in the CollateralProperties table.
        /// </summary>
        /// <param name="collateralProperty">A CollateralProperty entity object.</param>
        public void UpdateById(CollateralProperty collateralProperty)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.CollateralProperties " +
                "SET " +
                    "[product_id]=@product_id, " +
                    "[type_id]=@type_id, " +
                    "[name]=@name, " +
                    "[desc]=@desc " +
                "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@product_id", DbType.Int32, collateralProperty.product_id);
                db.AddInParameter(cmd, "@type_id", DbType.Int32, collateralProperty.type_id);
                db.AddInParameter(cmd, "@name", DbType.String, collateralProperty.name);
                db.AddInParameter(cmd, "@desc", DbType.String, collateralProperty.desc);
                db.AddInParameter(cmd, "@id", DbType.Int32, collateralProperty.id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the CollateralProperties table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.CollateralProperties " +
                                         "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the CollateralProperties table.
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>A CollateralProperty object with data populated from the database.</returns>
        public CollateralProperty SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [id], [product_id], [type_id], [name], [desc] " +
                "FROM dbo.CollateralProperties  " +
                "WHERE [id]=@id ";

            CollateralProperty collateralProperty = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new CollateralProperty
                        collateralProperty = new CollateralProperty();

                        // Read values.
                        collateralProperty.id = base.GetDataValue<int>(dr, "id");
                        collateralProperty.product_id = base.GetDataValue<int>(dr, "product_id");
                        collateralProperty.type_id = base.GetDataValue<int>(dr, "type_id");
                        collateralProperty.name = base.GetDataValue<string>(dr, "name");
                        collateralProperty.desc = base.GetDataValue<string>(dr, "desc");
                    }
                }
            }

            return collateralProperty;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the CollateralProperties table.
        /// </summary>
        /// <returns>A collection of CollateralProperty objects.</returns>		
        public List<CollateralProperty> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [product_id], [type_id], [name], [desc] " +
                "FROM dbo.CollateralProperties ";

            List<CollateralProperty> result = new List<CollateralProperty>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new CollateralProperty
                        CollateralProperty collateralProperty = new CollateralProperty();

                        // Read values.
                        collateralProperty.id = base.GetDataValue<int>(dr, "id");
                        collateralProperty.product_id = base.GetDataValue<int>(dr, "product_id");
                        collateralProperty.type_id = base.GetDataValue<int>(dr, "type_id");
                        collateralProperty.name = base.GetDataValue<string>(dr, "name");
                        collateralProperty.desc = base.GetDataValue<string>(dr, "desc");

                        // Add to List.
                        result.Add(collateralProperty);
                    }
                }
            }

            return result;
        }
    }
}

