//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// EconomicActivities data access component. Manages CRUD operations for the EconomicActivities table.
    /// </summary>
    public partial class EconomicActivityDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the EconomicActivities table.
        /// </summary>
        /// <param name="economicActivity">A EconomicActivity object.</param>
        /// <returns>An updated EconomicActivity object.</returns>
        public EconomicActivity Create(EconomicActivity economicActivity)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.EconomicActivities ([name], [parent_id], [deleted]) " +
                "VALUES(@name, @parent_id, @deleted); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@name", DbType.String, economicActivity.name);
                db.AddInParameter(cmd, "@parent_id", DbType.Int32, economicActivity.parent_id);
                db.AddInParameter(cmd, "@deleted", DbType.Boolean, economicActivity.deleted);

                // Get the primary key value.
                economicActivity.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return economicActivity;
        }

        /// <summary>
        /// Updates an existing row in the EconomicActivities table.
        /// </summary>
        /// <param name="economicActivity">A EconomicActivity entity object.</param>
        public void UpdateById(EconomicActivity economicActivity)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.EconomicActivities " +
                "SET " +
                    "[name]=@name, " +
                    "[parent_id]=@parent_id, " +
                    "[deleted]=@deleted " +
                "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@name", DbType.String, economicActivity.name);
                db.AddInParameter(cmd, "@parent_id", DbType.Int32, economicActivity.parent_id);
                db.AddInParameter(cmd, "@deleted", DbType.Boolean, economicActivity.deleted);
                db.AddInParameter(cmd, "@id", DbType.Int32, economicActivity.id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the EconomicActivities table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.EconomicActivities " +
                                         "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the EconomicActivities table.
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>A EconomicActivity object with data populated from the database.</returns>
        public EconomicActivity SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [id], [name], [parent_id], [deleted] " +
                "FROM dbo.EconomicActivities  " +
                "WHERE [id]=@id ";

            EconomicActivity economicActivity = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new EconomicActivity
                        economicActivity = new EconomicActivity();

                        // Read values.
                        economicActivity.id = base.GetDataValue<int>(dr, "id");
                        economicActivity.name = base.GetDataValue<string>(dr, "name");
                        economicActivity.parent_id = base.GetDataValue<int>(dr, "parent_id");
                        economicActivity.deleted = base.GetDataValue<bool>(dr, "deleted");
                    }
                }
            }

            return economicActivity;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the EconomicActivities table.
        /// </summary>
        /// <returns>A collection of EconomicActivity objects.</returns>		
        public List<EconomicActivity> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [name], [parent_id], [deleted] " +
                "FROM dbo.EconomicActivities ";

            List<EconomicActivity> result = new List<EconomicActivity>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new EconomicActivity
                        EconomicActivity economicActivity = new EconomicActivity();

                        // Read values.
                        economicActivity.id = base.GetDataValue<int>(dr, "id");
                        economicActivity.name = base.GetDataValue<string>(dr, "name");
                        economicActivity.parent_id = base.GetDataValue<int>(dr, "parent_id");
                        economicActivity.deleted = base.GetDataValue<bool>(dr, "deleted");

                        // Add to List.
                        result.Add(economicActivity);
                    }
                }
            }

            return result;
        }
    }
}

