//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// LinkPackagesExotics data access component. Manages CRUD operations for the LinkPackagesExotics table.
    /// </summary>
    public partial class LinkPackagesExoticDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the LinkPackagesExotics table.
        /// </summary>
        /// <param name="linkPackagesExotic">A LinkPackagesExotic object.</param>
        /// <returns>An updated LinkPackagesExotic object.</returns>
        public LinkPackagesExotic Create(LinkPackagesExotic linkPackagesExotic)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.LinkPackagesExotics ([package_id], [exotic_id]) " +
                "VALUES(@package_id, @exotic_id); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@package_id", DbType.Int32, linkPackagesExotic.package_id);
                db.AddInParameter(cmd, "@exotic_id", DbType.Int32, linkPackagesExotic.exotic_id);

                // Get the primary key value.
                linkPackagesExotic.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return linkPackagesExotic;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the LinkPackagesExotics table.
        /// </summary>
        /// <returns>A collection of LinkPackagesExotic objects.</returns>		
        public List<LinkPackagesExotic> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [package_id], [exotic_id] " +
                "FROM dbo.LinkPackagesExotics ";

            List<LinkPackagesExotic> result = new List<LinkPackagesExotic>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new LinkPackagesExotic
                        LinkPackagesExotic linkPackagesExotic = new LinkPackagesExotic();

                        // Read values.
                        linkPackagesExotic.id = base.GetDataValue<int>(dr, "id");
                        linkPackagesExotic.package_id = base.GetDataValue<int>(dr, "package_id");
                        linkPackagesExotic.exotic_id = base.GetDataValue<int>(dr, "exotic_id");

                        // Add to List.
                        result.Add(linkPackagesExotic);
                    }
                }
            }

            return result;
        }
    }
}

