//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// LoanDisbursmentEvents data access component. Manages CRUD operations for the LoanDisbursmentEvents table.
    /// </summary>
    public partial class LoanDisbursmentEventDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the LoanDisbursmentEvents table.
        /// </summary>
        /// <param name="loanDisbursmentEvent">A LoanDisbursmentEvent object.</param>
        /// <returns>An updated LoanDisbursmentEvent object.</returns>
        public LoanDisbursmentEvent Create(LoanDisbursmentEvent loanDisbursmentEvent)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.LoanDisbursmentEvents ([id], [amount], [fees], [interest]) " +
                "VALUES(@id, @amount, @fees, @interest);  ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, loanDisbursmentEvent.id);
                db.AddInParameter(cmd, "@amount", DbType.Currency, loanDisbursmentEvent.amount);
                db.AddInParameter(cmd, "@fees", DbType.Currency, loanDisbursmentEvent.fees);
                db.AddInParameter(cmd, "@interest", DbType.Currency, loanDisbursmentEvent.interest);

                db.ExecuteNonQuery(cmd);
            }

            return loanDisbursmentEvent;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the LoanDisbursmentEvents table.
        /// </summary>
        /// <returns>A collection of LoanDisbursmentEvent objects.</returns>		
        public List<LoanDisbursmentEvent> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [amount], [fees], [interest] " +
                "FROM dbo.LoanDisbursmentEvents ";

            List<LoanDisbursmentEvent> result = new List<LoanDisbursmentEvent>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new LoanDisbursmentEvent
                        LoanDisbursmentEvent loanDisbursmentEvent = new LoanDisbursmentEvent();

                        // Read values.
                        loanDisbursmentEvent.id = base.GetDataValue<int>(dr, "id");
                        loanDisbursmentEvent.amount = base.GetDataValue<decimal>(dr, "amount");
                        loanDisbursmentEvent.fees = base.GetDataValue<decimal>(dr, "fees");
                        loanDisbursmentEvent.interest = base.GetDataValue<decimal>(dr, "interest");

                        // Add to List.
                        result.Add(loanDisbursmentEvent);
                    }
                }
            }

            return result;
        }
    }
}

