//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// LoanShareAmounts data access component. Manages CRUD operations for the LoanShareAmounts table.
    /// </summary>
    public partial class LoanShareAmountDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the LoanShareAmounts table.
        /// </summary>
        /// <param name="loanShareAmount">A LoanShareAmount object.</param>
        /// <returns>An updated LoanShareAmount object.</returns>
        public LoanShareAmount Create(LoanShareAmount loanShareAmount)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.LoanShareAmounts ([person_id], [group_id], [contract_id], [amount], [event_id], [payment_date]) " +
                "VALUES(@person_id, @group_id, @contract_id, @amount, @event_id, @payment_date);  ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@person_id", DbType.Int32, loanShareAmount.person_id);
                db.AddInParameter(cmd, "@group_id", DbType.Int32, loanShareAmount.group_id);
                db.AddInParameter(cmd, "@contract_id", DbType.Int32, loanShareAmount.contract_id);
                db.AddInParameter(cmd, "@amount", DbType.Currency, loanShareAmount.amount);
                db.AddInParameter(cmd, "@event_id", DbType.Int32, loanShareAmount.event_id);
                db.AddInParameter(cmd, "@payment_date", DbType.DateTime, loanShareAmount.payment_date);

                db.ExecuteNonQuery(cmd);
            }

            return loanShareAmount;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the LoanShareAmounts table.
        /// </summary>
        /// <returns>A collection of LoanShareAmount objects.</returns>		
        public List<LoanShareAmount> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [person_id], [group_id], [contract_id], [amount], [event_id], [payment_date] " +
                "FROM dbo.LoanShareAmounts ";

            List<LoanShareAmount> result = new List<LoanShareAmount>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new LoanShareAmount
                        LoanShareAmount loanShareAmount = new LoanShareAmount();

                        // Read values.
                        loanShareAmount.person_id = base.GetDataValue<int>(dr, "person_id");
                        loanShareAmount.group_id = base.GetDataValue<int>(dr, "group_id");
                        loanShareAmount.contract_id = base.GetDataValue<int>(dr, "contract_id");
                        loanShareAmount.amount = base.GetDataValue<decimal>(dr, "amount");
                        loanShareAmount.event_id = base.GetDataValue<int>(dr, "event_id");
                        loanShareAmount.payment_date = base.GetDataValue<DateTime>(dr, "payment_date");

                        // Add to List.
                        result.Add(loanShareAmount);
                    }
                }
            }

            return result;
        }
    }
}

