//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// OverdueEvents data access component. Manages CRUD operations for the OverdueEvents table.
    /// </summary>
    public partial class OverdueEventDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the OverdueEvents table.
        /// </summary>
        /// <param name="overdueEvent">A OverdueEvent object.</param>
        /// <returns>An updated OverdueEvent object.</returns>
        public OverdueEvent Create(OverdueEvent overdueEvent)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.OverdueEvents ([id], [olb], [overdue_days], [overdue_principal]) " +
                "VALUES(@id, @olb, @overdue_days, @overdue_principal);  ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, overdueEvent.id);
                db.AddInParameter(cmd, "@olb", DbType.Currency, overdueEvent.olb);
                db.AddInParameter(cmd, "@overdue_days", DbType.Int32, overdueEvent.overdue_days);
                db.AddInParameter(cmd, "@overdue_principal", DbType.Currency, overdueEvent.overdue_principal);

                db.ExecuteNonQuery(cmd);
            }

            return overdueEvent;
        }

        /// <summary>
        /// Updates an existing row in the OverdueEvents table.
        /// </summary>
        /// <param name="overdueEvent">A OverdueEvent entity object.</param>
        public void UpdateById(OverdueEvent overdueEvent)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.OverdueEvents " +
                "SET " +
                    "[olb]=@olb, " +
                    "[overdue_days]=@overdue_days, " +
                    "[overdue_principal]=@overdue_principal " +
                "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@olb", DbType.Currency, overdueEvent.olb);
                db.AddInParameter(cmd, "@overdue_days", DbType.Int32, overdueEvent.overdue_days);
                db.AddInParameter(cmd, "@overdue_principal", DbType.Currency, overdueEvent.overdue_principal);
                db.AddInParameter(cmd, "@id", DbType.Int32, overdueEvent.id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the OverdueEvents table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.OverdueEvents " +
                                         "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the OverdueEvents table.
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>A OverdueEvent object with data populated from the database.</returns>
        public OverdueEvent SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [id], [olb], [overdue_days], [overdue_principal] " +
                "FROM dbo.OverdueEvents  " +
                "WHERE [id]=@id ";

            OverdueEvent overdueEvent = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new OverdueEvent
                        overdueEvent = new OverdueEvent();

                        // Read values.
                        overdueEvent.id = base.GetDataValue<int>(dr, "id");
                        overdueEvent.olb = base.GetDataValue<decimal>(dr, "olb");
                        overdueEvent.overdue_days = base.GetDataValue<int>(dr, "overdue_days");
                        overdueEvent.overdue_principal = base.GetDataValue<decimal>(dr, "overdue_principal");
                    }
                }
            }

            return overdueEvent;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the OverdueEvents table.
        /// </summary>
        /// <returns>A collection of OverdueEvent objects.</returns>		
        public List<OverdueEvent> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [olb], [overdue_days], [overdue_principal] " +
                "FROM dbo.OverdueEvents ";

            List<OverdueEvent> result = new List<OverdueEvent>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new OverdueEvent
                        OverdueEvent overdueEvent = new OverdueEvent();

                        // Read values.
                        overdueEvent.id = base.GetDataValue<int>(dr, "id");
                        overdueEvent.olb = base.GetDataValue<decimal>(dr, "olb");
                        overdueEvent.overdue_days = base.GetDataValue<int>(dr, "overdue_days");
                        overdueEvent.overdue_principal = base.GetDataValue<decimal>(dr, "overdue_principal");

                        // Add to List.
                        result.Add(overdueEvent);
                    }
                }
            }

            return result;
        }
    }
}

