//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// PersonsPhotos data access component. Manages CRUD operations for the PersonsPhotos table.
    /// </summary>
    public partial class PersonsPhotoDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the PersonsPhotos table.
        /// </summary>
        /// <param name="personsPhoto">A PersonsPhoto object.</param>
        /// <returns>An updated PersonsPhoto object.</returns>
        public PersonsPhoto Create(PersonsPhoto personsPhoto)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.PersonsPhotos ([person_id], [picture_id]) " +
                "VALUES(@person_id, @picture_id); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@person_id", DbType.Int32, personsPhoto.person_id);
                db.AddInParameter(cmd, "@picture_id", DbType.Int32, personsPhoto.picture_id);

                // Get the primary key value.
                personsPhoto.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return personsPhoto;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the PersonsPhotos table.
        /// </summary>
        /// <returns>A collection of PersonsPhoto objects.</returns>		
        public List<PersonsPhoto> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [person_id], [picture_id] " +
                "FROM dbo.PersonsPhotos ";

            List<PersonsPhoto> result = new List<PersonsPhoto>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new PersonsPhoto
                        PersonsPhoto personsPhoto = new PersonsPhoto();

                        // Read values.
                        personsPhoto.id = base.GetDataValue<int>(dr, "id");
                        personsPhoto.person_id = base.GetDataValue<int>(dr, "person_id");
                        personsPhoto.picture_id = base.GetDataValue<int>(dr, "picture_id");

                        // Add to List.
                        result.Add(personsPhoto);
                    }
                }
            }

            return result;
        }
    }
}

