//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// Provinces data access component. Manages CRUD operations for the Provinces table.
    /// </summary>
    public partial class ProvinceDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the Provinces table.
        /// </summary>
        /// <param name="province">A Province object.</param>
        /// <returns>An updated Province object.</returns>
        public Province Create(Province province)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.Provinces ([name], [deleted]) " +
                "VALUES(@name, @deleted); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@name", DbType.String, province.name);
                db.AddInParameter(cmd, "@deleted", DbType.Boolean, province.deleted);

                // Get the primary key value.
                province.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return province;
        }

        /// <summary>
        /// Updates an existing row in the Provinces table.
        /// </summary>
        /// <param name="province">A Province entity object.</param>
        public void UpdateById(Province province)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.Provinces " +
                "SET " +
                    "[name]=@name, " +
                    "[deleted]=@deleted " +
                "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@name", DbType.String, province.name);
                db.AddInParameter(cmd, "@deleted", DbType.Boolean, province.deleted);
                db.AddInParameter(cmd, "@id", DbType.Int32, province.id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the Provinces table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.Provinces " +
                                         "WHERE [id]=@id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the Provinces table.
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>A Province object with data populated from the database.</returns>
        public Province SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [id], [name], [deleted] " +
                "FROM dbo.Provinces  " +
                "WHERE [id]=@id ";

            Province province = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new Province
                        province = new Province();

                        // Read values.
                        province.id = base.GetDataValue<int>(dr, "id");
                        province.name = base.GetDataValue<string>(dr, "name");
                        province.deleted = base.GetDataValue<bool>(dr, "deleted");
                    }
                }
            }

            return province;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the Provinces table.
        /// </summary>
        /// <returns>A collection of Province objects.</returns>		
        public List<Province> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [name], [deleted] " +
                "FROM dbo.Provinces ";

            List<Province> result = new List<Province>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new Province
                        Province province = new Province();

                        // Read values.
                        province.id = base.GetDataValue<int>(dr, "id");
                        province.name = base.GetDataValue<string>(dr, "name");
                        province.deleted = base.GetDataValue<bool>(dr, "deleted");

                        // Add to List.
                        result.Add(province);
                    }
                }
            }

            return result;
        }
    }
}

