//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:44:45 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSaccoWeb.Entities;

namespace SBiSaccoWeb.Data
{
    /// <summary>
    /// UsersBranches data access component. Manages CRUD operations for the UsersBranches table.
    /// </summary>
    public partial class UsersBranchDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the UsersBranches table.
        /// </summary>
        /// <param name="usersBranch">A UsersBranch object.</param>
        /// <returns>An updated UsersBranch object.</returns>
        public UsersBranch Create(UsersBranch usersBranch)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.UsersBranches ([user_id], [branch_id]) " +
                "VALUES(@user_id, @branch_id);  ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@user_id", DbType.Int32, usersBranch.user_id);
                db.AddInParameter(cmd, "@branch_id", DbType.Int32, usersBranch.branch_id);

                db.ExecuteNonQuery(cmd);
            }

            return usersBranch;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the UsersBranches table.
        /// </summary>
        /// <returns>A collection of UsersBranch objects.</returns>		
        public List<UsersBranch> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [user_id], [branch_id] " +
                "FROM dbo.UsersBranches ";

            List<UsersBranch> result = new List<UsersBranch>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new UsersBranch
                        UsersBranch usersBranch = new UsersBranch();

                        // Read values.
                        usersBranch.user_id = base.GetDataValue<int>(dr, "user_id");
                        usersBranch.branch_id = base.GetDataValue<int>(dr, "branch_id");

                        // Add to List.
                        result.Add(usersBranch);
                    }
                }
            }

            return result;
        }
    }
}

